-- ==========================================
-- SCHEMA CREATION FOR SUPABASE PERSISTENCE
-- ==========================================

CREATE TABLE IF NOT EXISTS interactive_items (
    id TEXT PRIMARY KEY,
    source TEXT NOT NULL,
    completed BOOLEAN NOT NULL DEFAULT false,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE interactive_items ENABLE ROW LEVEL SECURITY;

-- RLS Policies for public access
DROP POLICY IF EXISTS "Allow public select" ON interactive_items;
CREATE POLICY "Allow public select" ON interactive_items FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public insert" ON interactive_items;
CREATE POLICY "Allow public insert" ON interactive_items FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public update" ON interactive_items;
CREATE POLICY "Allow public update" ON interactive_items FOR UPDATE USING (true);

-- ==========================================
-- INITIAL DATA SEEDING (POPULATION)
-- ==========================================

INSERT INTO interactive_items (id, source, completed)
VALUES
('act-0-1', 'itinerary', false),
('act-1-1', 'itinerary', false),
('act-1-2', 'itinerary', false),
('act-2-1', 'itinerary', false),
('act-3-1', 'itinerary', false),
('act-3-2', 'itinerary', false),
('act-4-1', 'itinerary', false),
('act-4-2', 'itinerary', false),
('act-4-3', 'itinerary', false),
('act-4-4', 'itinerary', false),
('act-4-5', 'itinerary', false),
('act-4-6', 'itinerary', false),
('act-5-1', 'itinerary', false),
('act-5-2', 'itinerary', false),
('act-5-3', 'itinerary', false),
('act-5-4', 'itinerary', false),
('act-6-1', 'itinerary', false),
('act-6-2', 'itinerary', false),
('act-6-3', 'itinerary', false),
('act-6-4', 'itinerary', false),
('act-6-5', 'itinerary', false),
('act-6-6', 'itinerary', false),
('act-6-7', 'itinerary', false),
('act-6-8', 'itinerary', false),
('act-6-9', 'itinerary', false),
('act-7-1', 'itinerary', false),
('act-7-2', 'itinerary', false),
('act-7-3', 'itinerary', false),
('act-7-4', 'itinerary', false),
('act-7-5', 'itinerary', false),
('act-7-6', 'itinerary', false),
('act-7-7', 'itinerary', false),
('act-7-8', 'itinerary', false),
('act-7-9', 'itinerary', false),
('act-7-10', 'itinerary', false),
('act-7-11', 'itinerary', false),
('act-7-12', 'itinerary', false),
('act-7-13', 'itinerary', false),
('act-8-1', 'itinerary', false),
('act-8-2', 'itinerary', false),
('act-8-3', 'itinerary', false),
('act-8-4', 'itinerary', false),
('act-8-5', 'itinerary', false),
('act-8-6', 'itinerary', false),
('act-8-7', 'itinerary', false),
('act-9-1', 'itinerary', false),
('act-9-2', 'itinerary', false),
('act-9-3', 'itinerary', false),
('act-9-4', 'itinerary', false),
('act-9-5', 'itinerary', false),
('act-9-6', 'itinerary', false),
('act-9-7', 'itinerary', false),
('act-9-8', 'itinerary', false),
('act-9-9', 'itinerary', false),
('act-9-10', 'itinerary', false),
('act-10-1', 'itinerary', false),
('act-10-2', 'itinerary', false),
('act-10-3', 'itinerary', false),
('act-10-4', 'itinerary', false),
('act-10-5', 'itinerary', false),
('act-10-6', 'itinerary', false),
('act-10-7', 'itinerary', false),
('act-10-8', 'itinerary', false),
('act-10-9', 'itinerary', false),
('act-10-10', 'itinerary', false),
('act-10-11', 'itinerary', false),
('act-10-12', 'itinerary', false),
('act-10-13', 'itinerary', false),
('act-11-1', 'itinerary', false),
('act-11-2', 'itinerary', false),
('act-11-3', 'itinerary', false),
('act-11-4', 'itinerary', false),
('act-11-5', 'itinerary', false),
('act-11-6', 'itinerary', false),
('act-11-7', 'itinerary', false),
('act-11-8', 'itinerary', false),
('act-11-9', 'itinerary', false),
('act-11-10', 'itinerary', false),
('act-11-11', 'itinerary', false),
('act-11-12', 'itinerary', false),
('act-12-1', 'itinerary', false),
('act-12-2', 'itinerary', false),
('act-12-3', 'itinerary', false),
('act-12-4', 'itinerary', false),
('act-12-5', 'itinerary', false),
('act-12-6', 'itinerary', false),
('act-12-7', 'itinerary', false),
('act-12-8', 'itinerary', false),
('act-13-1', 'itinerary', false),
('act-13-2', 'itinerary', false),
('act-13-3', 'itinerary', false),
('act-13-4', 'itinerary', false),
('act-13-5', 'itinerary', false),
('act-13-6', 'itinerary', false),
('act-13-7', 'itinerary', false),
('act-13-8', 'itinerary', false),
('act-14-1', 'itinerary', false),
('act-14-2', 'itinerary', false),
('act-14-3', 'itinerary', false),
('act-14-4', 'itinerary', false),
('act-14-5', 'itinerary', false),
('act-14-6', 'itinerary', false),
('act-14-7', 'itinerary', false),
('act-14-8', 'itinerary', false),
('act-14-9', 'itinerary', false),
('act-14-10', 'itinerary', false),
('act-14-11', 'itinerary', false),
('act-14-12', 'itinerary', false),
('act-14-13', 'itinerary', false),
('act-15-1', 'itinerary', false),
('act-15-2', 'itinerary', false),
('act-15-3', 'itinerary', false),
('act-15-4', 'itinerary', false),
('act-15-5', 'itinerary', false),
('act-15-6', 'itinerary', false),
('act-15-7', 'itinerary', false),
('act-15-8', 'itinerary', false),
('act-15-9', 'itinerary', false),
('act-16-1', 'itinerary', false),
('act-16-2', 'itinerary', false),
('act-16-3', 'itinerary', false),
('act-16-4', 'itinerary', false),
('act-16-5', 'itinerary', false),
('act-16-6', 'itinerary', false),
('act-16-7', 'itinerary', false),
('act-16-8', 'itinerary', false),
('act-16-9', 'itinerary', false),
('act-16-10', 'itinerary', false),
('act-16-11', 'itinerary', false),
('act-16-12', 'itinerary', false),
('act-16-13', 'itinerary', false),
('act-16-14', 'itinerary', false),
('act-17-1', 'itinerary', false),
('act-17-2', 'itinerary', false),
('act-17-3', 'itinerary', false),
('act-17-4', 'itinerary', false),
('act-17-5', 'itinerary', false),
('act-17-6', 'itinerary', false),
('act-17-7', 'itinerary', false),
('act-17-8', 'itinerary', false),
('act-17-9', 'itinerary', false),
('act-17-10', 'itinerary', false),
('act-17-11', 'itinerary', false),
('act-17-12', 'itinerary', false),
('act-17-13', 'itinerary', false),
('act-17-14', 'itinerary', false),
('act-18-1', 'itinerary', false),
('act-18-2', 'itinerary', false),
('act-18-3', 'itinerary', false),
('act-18-4', 'itinerary', false),
('act-18-5', 'itinerary', false),
('act-18-6', 'itinerary', false),
('act-18-7', 'itinerary', false),
('act-18-8', 'itinerary', false),
('act-18-9', 'itinerary', false),
('act-18-10', 'itinerary', false),
('act-19-1', 'itinerary', false),
('act-19-2', 'itinerary', false),
('act-19-3', 'itinerary', false),
('act-19-4', 'itinerary', false),
('act-19-5', 'itinerary', false),
('act-19-6', 'itinerary', false),
('act-19-7', 'itinerary', false),
('act-19-8', 'itinerary', false),
('act-19-9', 'itinerary', false),
('act-19-10', 'itinerary', false),
('act-19-11', 'itinerary', false),
('act-20-1', 'itinerary', false),
('act-21-1', 'itinerary', false),
('act-21-2', 'itinerary', false),
('act-21-3', 'itinerary', false),
('act-21-4', 'itinerary', false),
('act-21-5', 'itinerary', false),
('act-21-6', 'itinerary', false),
('act-21-7', 'itinerary', false),
('act-21-8', 'itinerary', false),
('act-21-9', 'itinerary', false),
('act-21-10', 'itinerary', false),
('act-21-11', 'itinerary', false),
('act-21-12', 'itinerary', false),
('act-21-13', 'itinerary', false),
('act-21-14', 'itinerary', false),
('act-21-15', 'itinerary', false),
('act-21-16', 'itinerary', false),
('act-22-1', 'itinerary', false),
('act-22-2', 'itinerary', false),
('act-22-3', 'itinerary', false),
('act-22-4', 'itinerary', false),
('act-22-5', 'itinerary', false),
('act-22-6', 'itinerary', false),
('act-22-7', 'itinerary', false),
('act-22-8', 'itinerary', false),
('act-23-1', 'itinerary', false),
('act-23-2', 'itinerary', false),
('act-23-3', 'itinerary', false),
('act-23-4', 'itinerary', false),
('act-23-5', 'itinerary', false),
('act-23-6', 'itinerary', false),
('act-23-7', 'itinerary', false),
('act-23-8', 'itinerary', false),
('act-23-9', 'itinerary', false),
('act-23-10', 'itinerary', false),
('act-23-11', 'itinerary', false),
('act-23-12', 'itinerary', false),
('act-23-13', 'itinerary', false),
('act-23-14', 'itinerary', false),
('act-23-15', 'itinerary', false),
('act-24-1', 'itinerary', false),
('todo-tram-1', 'todo', false),
('todo-tram-2', 'todo', false),
('todo-tram-3', 'todo', false),
('todo-tram-4', 'todo', false),
('todo-tram-5', 'todo', false),
('todo-res-1', 'todo', false),
('todo-res-2', 'todo', false),
('todo-res-3', 'todo', false),
('todo-res-4', 'todo', false),
('todo-log-1', 'todo', false),
('todo-log-2', 'todo', false),
('todo-log-3', 'todo', false),
('todo-log-4', 'todo', false),
('pack-docs-1', 'packing', false),
('pack-docs-2', 'packing', false),
('pack-docs-3', 'packing', false),
('pack-docs-4', 'packing', false),
('pack-docs-5', 'packing', false),
('pack-tech-1', 'packing', false),
('pack-tech-2', 'packing', false),
('pack-tech-3', 'packing', false),
('pack-tech-4', 'packing', false),
('pack-tech-5', 'packing', false),
('pack-clothes-1', 'packing', false),
('pack-clothes-2', 'packing', false),
('pack-clothes-3', 'packing', false),
('pack-clothes-4', 'packing', false),
('pack-clothes-5', 'packing', false),
('pack-fam-1', 'packing', false),
('pack-fam-2', 'packing', false),
('pack-fam-3', 'packing', false),
('pack-fam-4', 'packing', false),
('pack-toil-1', 'packing', false),
('pack-toil-2', 'packing', false),
('pack-toil-3', 'packing', false),
('pack-toil-4', 'packing', false),
('pack-toil-5', 'packing', false)
ON CONFLICT (id) DO NOTHING;
